export const FETCH_EMOTION_DATA = "FETCH_EMOTION_DATA";
export const NEW_DATA = "NEW_DATA";
export const FETCH_SUCCESS_DATA = "FETCH_SUCCESS_DATA";
export const FETCH_SUGGESTION_DATA = "FETCH_SUGGESTION_DATA";
export const FETCH_DATA = "FETCH_DATA";

export const FETCHING_ANALYSIS_DATA = "FETCHING_ANALYSIS_DATA";
export const FETCHING_ANALYSIS_DATA_SUCCESSFUL =
  "FETCHING_ANALYSIS_DATA_SUCCESSFUL";
export const FETCHING_ANALYSIS_DATA_FAILED = "FETCHING_ANALYSIS_DATA_FAILED";
